### ISSUE TITLE
Export Name as well, if exists, from Member Table

### ISSUE THREAD

**Issue by emkayy** [lionel-m/newsletter-export#1]
\system\modules\newsletter_export\classes\NewsletterExport.php line 45:
``` $objRow = $this->Database->prepare("SELECT (SELECT CONCAT_WS(' ', firstname, lastname) FROM tl_member WHERE email = n.email),email,active FROM tl_newsletter_recipients AS n WHERE pid=? ORDER by email") ```

Line 64:
``` $output .= '"Name","E-mail","Active"'. "\n" ; ```

Maybe you could even split it in 2 or include more fields like gender etc. for real personalized emails.

**Comment by fritzmg** [comment]
I have created a pull request for this feature: #2

**Comment by lionel-m** [comment]
I closed the ticket in favor of the PR #2
