### ISSUE TITLE
Version for Contao 3.5.x

### ISSUE THREAD

**Issue by frontendschlampe** [lionel-m/newsletter-export#3]
Is there any version of newsletter-export for Contao 3.5.x - maybe you could make a beta version so that I can install via composer to check! Thank you!

**Comment by lionel-m** [comment]
Hi,
I've modified the `composer.json` file and updated the release [3.1.0](https://github.com/lionel-m/newsletter-export/releases/tag/3.1.0). Tested with Contao 3.5.12.

**Comment by frontendschlampe** [comment]
Thank you ... I will try it soon ...
